# Generated by Django 5.2.8 on 2025-11-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_combo_description_combo_is_available_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="combo",
            name="price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.IntegerField(),
        ),
    ]
