# Generated by Django 5.2.8 on 2025-11-25 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_alter_combo_price_alter_menuitem_price"),
        ("orders", "0006_alter_order_status_delete_ordercombo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Combo",
        ),
    ]
