# Generated by Django 5.2.8 on 2025-11-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_delete_combo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Combo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("description", models.TextField(blank=True)),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
    ]
