# Generated by Django 4.2.7 on 2025-12-01 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_status_delete_ordercombo'),
        ('menu', '0005_combo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Combo',
        ),
    ]
