# Generated by Django 4.2.7 on 2025-12-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_delete_combo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
