# Generated by Django 5.2.8 on 2025-11-20 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_order_number_alter_order_status"),
    ]

    operations = []
