# Generated by Django 5.2.8 on 2025-11-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_auto_20251120_2152"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="OrderCombo",
        ),
    ]
