# Generated by Django 4.2.7 on 2025-12-01 08:58

from django.db import migrations, models
import django.db.models.deletion


def populate_item_names(apps, schema_editor):
    OrderItem = apps.get_model('orders', 'OrderItem')
    for order_item in OrderItem.objects.all():
        if not order_item.item_name:
            name = ''
            if order_item.item_id:
                name = order_item.item.name
            order_item.item_name = name or 'Item'
            order_item.save(update_fields=['item_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_delete_combo'),
        ('orders', '0009_alter_orderitem_item_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_name',
            field=models.CharField(blank=True, default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.menuitem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.RunPython(populate_item_names, migrations.RunPython.noop),
    ]
